[workspace]
resolver = "2"
members = [
    "crates/rl-utils",
    "crates/rl-lexer",
    "crates/rl-ast",
    "crates/rl-parser",
    "crates/rl-resolver",
    "crates/rl-vm",
    "crates/rl-std-core",
    "crates/rl-std-macros",
    "crates/rl-std",
    "crates/rl-embed",
    "crates/rl-tests",
]

[workspace.package]
version = "1.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
rl-utils = { path = "crates/rl-utils", version = "1.2.0" }
rl-lexer = { path = "crates/rl-lexer", version = "1.2.0" }
rl-ast = { path = "crates/rl-ast", version = "1.2.0" }
rl-parser = { path = "crates/rl-parser", version = "1.2.0" }
rl-resolver = { path = "crates/rl-resolver", version = "1.2.0" }
rl-vm = { path = "crates/rl-vm", version = "1.2.0" }
rl-std-core = { path = "crates/rl-std-core", version = "1.2.0" }
rl-std-macros = { path = "crates/rl-std-macros", version = "1.2.0" }
rl-std = { path = "crates/rl-std", version = "1.2.0" }
rl-embed = { path = "crates/rl-embed", version = "1.2.0" }

hashbrown = { version = "0.15", default-features = false, features = ["default-hasher"] }
ryu = "1"
libm = "0.2"
miniz_oxide = { version = "0.8", default-features = false, features = ["with-alloc"] }

syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
