[package]
name = "rl-vm"
version.workspace = true
readme = "readme.md"
edition.workspace = true
license.workspace = true
description = "Bytecode virtual machine for the embedded RL programming language"

[dependencies]
rl-ast.workspace = true
rl-lexer.workspace = true
rl-parser.workspace = true
rl-resolver.workspace = true
rl-utils.workspace = true
rl-std-core.workspace = true
rl-std.workspace = true
hashbrown.workspace = true
ryu.workspace = true
miniz_oxide.workspace = true