[package]
name = "rl-std"
version.workspace = true
readme = "readme.md"
edition.workspace = true
license.workspace = true
description = "The runtime-agnostic standard library for the embedded RL engine (pure-computation modules only)"

[dependencies]
rl-std-core.workspace = true
rl-std-macros.workspace = true
rl-ast.workspace = true
rl-utils.workspace = true
libm.workspace = true