[package]
name = "rl-parser"
version.workspace = true
readme = "readme.md"
edition.workspace = true
license.workspace = true
description = "Parser for the embedded RL programming language"

[dependencies]
rl-ast.workspace = true
rl-lexer.workspace = true
rl-utils.workspace = true
hashbrown.workspace = true